### ISSUE TITLE
KeyError at Line 38 & Line 44

### ISSUE THREAD

**Issue by KnightCoder27** [shukl08vk/Cricket-Score-Alert-on-Telegram#1]
You have used " r['liveSummary']['batsmen'] " in the line 38 However the correct and Actual Iine is " r['supportInfo']['liveSummary']['batsmen'] "

Same goes for Line 44, Instead of using " r['liveSummary']['bowlers'] ", use r['supportInfo']['liveSummary']['bowlers'].

Hope you will modify this in your code.
By the way, Thanks for this code it really helped me to finish my Mini Project.

Ciao, 
X_X

**Comment by Aniket01k** [comment]
Bro is this code working or not .I try to run this code but it's not working only showing the match name  !! So can you tell me what is the problem .

**Comment by shukl08vk** [comment]
> You have used " r['liveSummary']['batsmen'] " in the line 38 However the correct and Actual Iine is " r['supportInfo']['liveSummary']['batsmen'] "
> 
> Same goes for Line 44, Instead of using " r['liveSummary']['bowlers'] ", use r['supportInfo']['liveSummary']['bowlers'].
> 
> Hope you will modify this in your code. By the way, Thanks for this code it really helped me to finish my Mini Project.
> 
> Ciao, X_X

**Comment by shukl08vk** [comment]
> You have used " r['liveSummary']['batsmen'] " in the line 38 However the correct and Actual Iine is " r['supportInfo']['liveSummary']['batsmen'] "
> 
> Same goes for Line 44, Instead of using " r['liveSummary']['bowlers'] ", use r['supportInfo']['liveSummary']['bowlers'].
> 
> Hope you will modify this in your code. By the way, Thanks for this code it really helped me to finish my Mini Project.
> 
> Ciao, X_X

Hi Ciao,

This is the normal scenario here because these are dynamic websites and the contents would be change due to the execution of JavaScript that changes the HTML elements on the page.

**Comment by Aniket01k** [comment]
So do you have working code i got project on that
But i try do much but i can't complete it
